[package]
name = "sha256-bench-rust"
version = "0.1.0"
authors = ["Evgeny Beskonchin <evgeny@beskonchin.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
