[package]
name = "sha256-bench-rust"
description = "Benchmark for SHA256 calculation"
version = "0.1.0"
authors = ["Evgeny Beskonchin <evgeny@beskonchin.info>"]
edition = "2018"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
rayon = "1.10.0"